### ISSUE TITLE
What does the 'event_link_set_all_poi_type_feature_coarse_beijing_1km.pkl' mean? 

### ISSUE THREAD

**Issue by dddssy** [JingqingZ/BaiduTraffic#10]
I check the your codes, in function load_data, you open files: "event_traffic_beijing_1km_mv_avg_15min_completion.pkl" & "event_link_set_all_poi_type_feature_fine_beijing_1km.pkl" &'event_link_set_all_beijing_1km_link_info_feature.pkl&'', but how this data files coming from. In other words, how can i get these data.
Thanks!

**Comment by bbliao** [comment]
you can see the wide_feature_readme.md and wide_feature_1km.zip in the https://github.com/JingqingZ/BaiduTraffic/tree/wide-feature-extraction/data for more details.

**Comment by vision-zhao** [comment]
I'm wondering that how can I run the codes you released in BaiduTraffic-Master and then obtain the results you mentioned in the paper?

because the data released is not matching with the data used in the codes, I feel confused about this.  
Look forward to your reply.Thanks

**Comment by bbliao** [comment]
@vision-zhao We are sorry for the inconvenience of the codes because of the differences between the formats of original dataset and released dataset. We will consider releasing the temp files at the pan.baidu.com or rewrite the pre-processing codes for the released dataset when we are free. 
Before that, you may rewrite the pre-processing codes, since the released pre-processing codes are not complex. Thanks for your attention!
