### ISSUE TITLE
Duplicate links in Road_network_sub-dataset but with different properties

### ISSUE THREAD

**Issue by panwangwin** [JingqingZ/BaiduTraffic#18]
I want to process your data to reveal some graph structure. But I found there are duplicate link_ids in road_network_sub-dataset and those links are totally with different value of width snodeid enodeid or length. I am quite confusing how this could happen.
Following are some link_ids I found duplicated in road_network_sub-dataset
<class 'list'>: [1014574024344, 1163808777119, 1573596569624, 1490171293608, 1144042225780, 1934286704917]

**Comment by bbliao** [comment]
@panwangwin Sorry for the mistakes in the dataset. This is caused by the hash function which sometimes maps the different original link_ids into the same id. I will fix that soon and re-upload the dataset.

**Comment by panwangwin** [comment]
@bbliao Thanks for replying! Please inform me when you update all of your dataset.

**Comment by bbliao** [comment]
@panwangwin We have updated the dataset, and it is now available at [BaiduNetDisk](https://pan.baidu.com/s/1s1bauEJs8ONtC65ZkC4N3A) Code：umqd. 

For those who have downloaded the old dataset, we strongly suggest you re-download the updated dataset. The old dataset at Baidu Research Open-Access Dataset (BROAD) exists some duplicated hashed_link_id due to the hash function. So the hashed_link_id is removed in the updated dataset, meaning that we just use the `link_id` which is consistent with the [intermediate\_files](intermediate_files).

Thanks for pointing out the mistake! Feel free to ask me if I missed something.

**Comment by panwangwin** [comment]
@bbliao Hi l am currently using Ubuntu Desktop, and the BaiduNetDisk is not really friendly to Linux users. So when will you update you dataset on BROAD. That's more available to me. Thank you.

**Comment by bbliao** [comment]
@panwangwin I have left from Baidu, so it is difficult to upload the dataset on BROAD. I am trying to upload the dataset on the google drive, but it may take 48 hours.
