### ISSUE TITLE
It is described in the paper there will be snode_gps and enode_gps but there is only link_gps in the file.

### ISSUE THREAD

**Issue by panwangwin** [JingqingZ/BaiduTraffic#20]
How could I transfer link_gps to nodes_gps?  Can you release the dataset including the nodes_gps?

**Comment by panwangwin** [comment]
I have examine some of the previous issues about the gps. I found it is said that the snode and enode are also links. So they are in the link_gps file.
But through my exploration. I cannot find the any nodes id in the link_gps file. I can only find link ids in link_gps file. And I find the snodeids and enodeids are only appears at "node" columns in the road_network_sub-dataset which I think is implying the snode and enode are not links? 
I want to generate the topology of the dataset. So the gps is important to locate nodes in a graph.
Really appreciate if you can reply soon.

**Comment by bbliao** [comment]
@panwangwin 
You may find [issue 16](https://github.com/JingqingZ/BaiduTraffic/issues/16) useful.
1. As it is said, snode and enode are also links;
2. We can not provide the complete road network due to data incompleteness (not all the missing rate of the road segments are less than 1%), privacy and security.
Thanks for your attention!

**Comment by JingqingZ** [comment]
This issue is closed now. Please feel free to reopen it if any further problem.
