### ISSUE TITLE
Still questions about enode and snode

### ISSUE THREAD

**Issue by panwangwin** [JingqingZ/BaiduTraffic#21]
#20 
Hi, thank you about the issues before, but I still get some questions here.
I am trying to recover the topology of the dataset. I want to construct a graph represent the spatial information with G(V,E) where V is vertices and E is Edges. Firstly I consider snode and enode can be mapped as vertices and links can be mapped as edges. Like this:
![bmASDgRwQdK9uiUYJ3Tu1Q_thumb_1867](https://user-images.githubusercontent.com/16345740/61579328-45414580-ab36-11e9-8c87-7c626d171723.jpg)
The outlines represent true road and the thin lines can be seen as links and the big dots can be seen as nodes(snode or enode). But it is said in issue  #16 the snode and enode are also links. So that confused me if the snode and enode are also links. It may cause some vague representations when situation like below happens:
![zZX7s4Z8R2iIWB+8J%9GBw_thumb_1864](https://user-images.githubusercontent.com/16345740/61579396-02cc3880-ab37-11e9-9f4e-e3ab2e883a4f.jpg)
The link in the middle are connect with 6 links. And I need 2 of them to represent the enode and snode of such link.I am not sure which links I should choose to represent.
Using the illustration in issue #16 like below. If we add link2 link3 and link4, for link2, one of the (link1,enode) could be the snode of the link2, one of the (link3,link4) could be the enode of the link2. If so, it will really hard to recover the topology of the dataset in G(V,E) form. Because I can only get Edge information but not Vertices. And I am not sure, if all those snode and enode are links, what should be consider as vertices in graph.
![Ed5M0p1bSZy7UvnA2Cs1xQ_thumb_1863](https://user-images.githubusercontent.com/16345740/61577718-f25b9400-ab1d-11e9-9d79-42eec5d76301.jpg)

Hoping you reply.
Thank you.

**Comment by bbliao** [comment]
@panwangwin 
1. A link is a small segment of the road. As the illustration in issue #16,  snode, enode and center link are all link. In real-world applications, the basic unit of the traffic condition is link. such as [Baidu Map](https://map.baidu.com/@12959238.56,4825347.47,12z/maplayer%3Dtrafficrealtime), [Gaode map](https://map.gaode.com/).
2. As for the G(V,E) form, the link is regarded as the node, while the connection(e.g., <snode, link>, <link, enode>) is regarded as the edge.
3. We can not release the whole road network because of data privacy and data incompleteness (not all the links in the road network have recorded their traffic speed at all the timestamps). 

Thanks for your attention.

**Comment by JingqingZ** [comment]
Please feel free to reopen it if any further question. Closed for now.
