### ISSUE TITLE
Connetion between the Baidu's "Traffic Speed Sub-dataset" /" Road Network Sub-dataset" and the files used in your codes 

### ISSUE THREAD

**Issue by paladin2000cn** [JingqingZ/BaiduTraffic#7]
I check the your codes,  in function load_data, you open files: "event_traffic_beijing_1km_mv_avg_15min_completion.pkl" & "neighbours_1km.txt" , but how this data files coming from. I just check for Q-Traffic Dataset, only 3 Sub-datasets used . so do there are raw data pre-pocessing codes that are not included in github now?

thanks!
BR,
James

**Comment by bbliao** [comment]
@paladin2000cn Thanks for your interest in our work. Yes, there are some raw data pre-processing codes that are not included in Github. 
Since the released dataset are pre-processed for simplicity and readability, they are not the same as the raw data in the format (but the content are the same). So we did not release all the raw data pre-processing codes. 
As for the files you mentioned,
1. the "event_traffic_beijing_1km_mv_avg_15min_completion.pkl" is a dictionary, with the key is "link_id" and the value is a list of length 17,568, representing the traffic speed of the link at each time stamp. (just as the traffic_speed_sub-dataset).
2. the "neighbours_1km.txt" has been uploaded at the root directory.

Thank you!
Binbing Liao

**Comment by paladin2000cn** [comment]
thanks
